extract:
  history:
    start_date: 2019-05-18
    end_date: 2021-07-29
    validation_days_max_date: 2021-05-18
transform:
  fundamentalista:
    max_date: 2021-05-18
model:
  grid_search:
    train:
      # O max_date tem o mesmo valor do predict
      # pq o grid search funciona com index dos
      # dados de validação. Por isso é carregado
      # todo o X_train
      max_date: 2021-06-28
    experiments:
      1_day:
        start_date: 2021-05-19
        end_date: 2021-05-19
      7_days:
        start_date: 2021-05-19
        end_date: 2021-05-27
      14_days:
        start_date: 2021-05-19
        end_date: 2021-06-08
      28_days:
        start_date: 2021-05-19
        end_date: 2021-06-29
  predict:
    train:
      # O predict incorpora os dados de validação
      # da etapa de GS
      max_date: 2021-06-29
    experiments:
      1_day:
        start_date: 2021-06-30
        end_date: 2021-06-30
      7_days:
        start_date: 2021-06-30
        end_date: 2021-07-08
      14_days:
        start_date: 2021-06-30
        end_date: 2021-07-20
      28_days:
        start_date: 2021-06-30
        end_date: 2021-07-29

