extract:
  history:
    start_date: 2019-05-18
    end_date: 2021-07-28
    validation_days_max_date: 2021-05-18
transform:
  fundamentalista:
    max_date: 2021-05-18
model:
  grid_search:
    train:
      max_date: 2021-05-18
  predict:
    train:
      max_date: 2021-06-18

